stages:
  - develoment
develoment:
  only:
    - master
  stage: develoment
  script:
    - docker login registry.fibo.cloud -p ${DOCKER_PWD} -u ${DOCKER_USERNAME}
    - time DOCKER_BUILDKIT=1 docker build -t registry.fibo.cloud/exa/photobook-frontend .
    - docker ps --quiet --filter="name=photobook-frontend" | xargs --no-run-if-empty docker rm -f
    - docker push registry.fibo.cloud/exa/photobook-frontend
    - docker run -dt -p 84:80 --restart always --name photobook-frontend registry.fibo.cloud/exa/photobook-frontend
    - docker system prune -f

  environment:
    name: staging
    url: http://photobook.fibo.cloud/

  tags:
    - exa_fibo
